###

POST http://localhost:5000/api/producto HTTP/1.1
Content-Type: application/json

{

      "codigo": "24",
      "urlImagen": "https://www.itrush.com/wp-content/uploads/2015/04/The-Elliptical-Bicycle-2.jpg.webp",
      "nombre": "bicicleta Modificada ",
      "descripcion": "Esta bicicleta de ejercicios incluso cuenta con un sistema de 3 marchas que permite al propietario escalar en niveles moderados",
      "características": "Frenos de mano,un marco resistente que se pliega fácilmente a la mitad, llantas delanteras con 16 pulgadas y traseras con 20 pulgadas.  ",
      "precio": 12877656,
      "stock" :0,
      "categoriaId": 1

}

###
POST http://localhost:5000/api/carrito HTTP/1.1
Content-Type: application/json

{
      "codigo": "1",
      "urlImagen": "https://http2.mlstatic.com/D_NQ_NP_905295-MCO48918988539_012022-O.webp",
      "nombre": "Bicicleta todo terreno",
      "cantidad": 1,
      "valor": 1500000
}

###
GET http://localhost:5000/api/producto HTTP/1.1

###
GET http://localhost:5000/api/productostock HTTP/1.1

###
DELETE http://localhost:5000/api/producto/6370402435b3398af3631c7d HTTP/1.1

###
PUT http://localhost:5000/api/producto/637035cf63227b4521b38dd1 HTTP/1.1
Content-Type: application/json

{
    "codigo": "2",
    "urlImagen": "https://i.pinimg.com/originals/6b/05/ec/6b05ecf274a6e9c0ec52b6c71a75426a.jpg",
    "nombre": "Bicicleta BMX",
    "descripcion": "Un solo sistema de frenado (situado en las ruedas traseras)",
    "características": ", cuadros de 20 pulgadas, de aluminio y acero, 22 y 25 dientes en el plato y un solo piñón de 9 y 11 dientes",
    "precio": 1285000,
    "stock": 0,
    "categoriaId": 1
}
